ApexLogs/force-app/main/default/objects/apex_log_event__e/apex_log_event__e.object-meta.xml
<CustomObject>
    <label>apex log event</label>
    <pluralLabel>apex log events</pluralLabel>
</CustomObject>

ApexLogs/force-app/main/default/objects/apex_log_event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Contains information about why the event was created</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ApexLogs/force-app/main/default/objects/apex_log_event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of the log. Options are Error, Information, Warning</description>
    <label>Type</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ApexLogs/force-app/main/default/classes/ApexLogs.cls
public with sharing class ApexLogs implements IApexLogs {
    
    public ApexLogs() {

    }

    public void logInformation(string message){
        
        createApexLogEvent('information', message);

    }

    public void logWarning(string message){

        createApexLogEvent('warning', message);

    }

    public void logError(string message){

        createApexLogEvent('error', message);

    }

    private void createApexLogEvent(string logType, string message){

        List<Apex_Log_Event__e> events = new List<Apex_Log_Event__e>();
        events.add(new Apex_Log_Event__e(Type__c = logType, Message__c = message));

        List<Database.SaveResult> results = EventBus.publish(events);

        for (Database.SaveResult sr : results) {
        if (sr.isSuccess()) {
            System.debug('Successfully published event.');
        } else {
            for(Database.Error err : sr.getErrors()) {
                System.debug('Error returned: ' +
                            err.getStatusCode() +
                            ' - ' +
                            err.getMessage());
            }
        }       
        }
    }
}